package Modelos;
// Generated 26/03/2021 03:25:54 PM by Hibernate Tools 4.3.1

import java.util.List;




/**
 * TbPersonas generated by hbm2java
 */
public class TbPersonas  implements java.io.Serializable {


     private Integer idTbPersonas;
     private String nombre;

    public TbPersonas() {
    }

    public TbPersonas(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdTbPersonas() {
        return this.idTbPersonas;
    }
    
    public void setIdTbPersonas(Integer idTbPersonas) {
        this.idTbPersonas = idTbPersonas;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }





}


